/** This file is generated by tool. Please do not modify it. **/

import "./Test/UI_bt_close.ts"
import "./Test/UI_TaskDialog.ts"


export class FairyGUIHelper {
	/** 初始化 FairyGUI */
	static init() {
		FairyGUIHelper.bindAll();
		fairygui.UIConfig.packageFileExtension = "bin";
		Laya.stage.addChild(fairygui.GRoot.inst.displayObject);
	}

	/** 绑定 UI 与脚本类 */
	static bind(url: string, viewClass: any) {
		fairygui.UIObjectFactory.setPackageItemExtension(url, viewClass);
	}

	/** 加载 FairyGUI 的包 */
	static loadPackage(pkg: string, atlas:string|string[], completeHandle?: Laya.Handler) {
		let res_list = [{ url: pkg, type: Laya.Loader.BUFFER }];
		if (typeof(atlas) === 'string') {
			res_list.push({url: atlas, type: Laya.Loader.IMAGE});
		} else if (atlas.length){
			for (const url of atlas) {
				res_list.push({url, type: Laya.Loader.IMAGE});
			}
		}
		const callback = {
			complete: function() {
				fairygui.UIPackage.addPackage(pkg.split('.').slice(0, -1).join('.'), Laya.loader.getRes(pkg));
				if(completeHandle) {
					completeHandle.run();
				}
			}
		};
		Laya.loader.load(res_list, Laya.Handler.create(callback, callback.complete));
	}

	/** 绑定所有UI与工具生成的脚本类 */
	static bindAll() {
		FairyGUIHelper.bind(Test.UI_bt_close.URL, Test.UI_bt_close);
		FairyGUIHelper.bind(Test.UI_TaskDialog.URL, Test.UI_TaskDialog);

	}
}
